#!/usr/bin/env bash
#
# Builds the gVisor netstack bridge into app/libs/netstack.aar using gomobile.
#
# This recipe is VERIFIED working (2026-07-23): it produced a 3.8 MB arm64 AAR
# that the app links against successfully (./gradlew assembleDebug -Pnetvalve.netstack=true).
#
# Requirements (host):
#   - Go with automatic toolchain download enabled (GOTOOLCHAIN=auto). The build
#     pulls the exact Go the modules need (>=1.25 at time of writing).
#   - Android NDK  (export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/<version>, e.g. 27.x)
#   - JDK 17
#
# Why the sagernet/gvisor fork:
#   Upstream gvisor.dev/gvisor is NOT buildable with plain `go build`/gomobile —
#   its intrusive lists / refcounts / marshal code is generated by its Bazel build
#   and not committed, and its `pkg/sync` ships un-processed `.tmpl.s` template
#   assembly. github.com/sagernet/gvisor is the maintained, plain-go-buildable fork
#   used by sing-box / tun2socks; it commits the generated files and builds with
#   gomobile out of the box. See docs/NETSTACK_EVIDENCE.md.
#
# Usage:
#   export ANDROID_NDK_HOME=/path/to/ndk
#   cd netstack && ./build-aar.sh [arm64|all]
#
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="$HERE/../app/libs"
OUT_AAR="$OUT_DIR/netstack.aar"
TARGETS="${1:-arm64}"   # 'arm64' (default, real devices) or 'all' (adds amd64/x86 for emulators)

echo "==> Toolchain"
command -v go >/dev/null || { echo "Go not found. Install Go (GOTOOLCHAIN=auto will fetch the right version)."; exit 1; }
: "${ANDROID_NDK_HOME:?Set ANDROID_NDK_HOME to your Android NDK path}"
export GOTOOLCHAIN="${GOTOOLCHAIN:-auto}"
go version

echo "==> Resolve modules"
go mod tidy

echo "==> Compile check (host arch, no cgo) before binding"
GOFLAGS=-mod=mod go build ./...

echo "==> Install gomobile + gobind"
go install golang.org/x/mobile/cmd/gomobile@latest
go install golang.org/x/mobile/cmd/gobind@latest
export PATH="$(go env GOPATH)/bin:$PATH"

case "$TARGETS" in
  all) TARGET="android/arm64,android/arm,android/amd64,android/386" ;;
  *)   TARGET="android/arm64" ;;
esac

echo "==> gomobile bind ($TARGET) -> $OUT_AAR"
mkdir -p "$OUT_DIR"
# -javapkg dev.netvalve  => generated Java package dev.netvalve.bridge
GOFLAGS=-mod=mod gomobile bind \
  -target="$TARGET" \
  -androidapi 29 \
  -javapkg=dev.netvalve \
  -o "$OUT_AAR" \
  .

echo "==> Done: $OUT_AAR"
ls -la "$OUT_AAR"
echo "Now build the app with:  ./gradlew :app:assembleDebug -Pnetvalve.netstack=true"
